# Uncomment the next line to define a global platform for your project
platform :ios, '14.3'

target 'Library Management' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Library Management

  target 'Library ManagementTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Library ManagementUITests' do
    # Pods for testing
  end

  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Analytics'
  pod 'Firebase/Firestore'
  pod 'Firebase/Database' 

end
